### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by jrrcdev** [jonatanrinckus/GitClient#3]
This is an issue test for test the new application.

`public void Foo(){
Console.WriteLine("Foooooooooooooooooo");
}`

**Comment by jrrcdev** [comment]
Another test

**Comment by jrrcdev** [comment]
Comment Test

**Comment by jrrcdev** [comment]
Commenting by GitClient

**Comment by jrrcdev** [comment]
Test

Commented with GitClient by BeDatse.

**Comment by jrrcdev** [comment]
<strong>Test</strong>

**Comment by jrrcdev** [comment]
**Test**

**Comment by jrrcdev** [comment]
<bold>test</bold>

**Comment by jrrcdev** [comment]
<b>test</b>

**Comment by jrrcdev** [comment]
TEssssssssssssssst

<strong>Posted with GitClient by BeDatse.</strong>

**Comment by jrrcdev** [comment]
Test 01000

<strong>Posted with GitClient by BeDatse.</strong>

**Comment by jrrcdev** [comment]
Comment test

<strong>Posted with GitClient by BeDatse.</strong>

**Comment by jrrcdev** [comment]
Comentando pelo programa

<strong>Posted with GitClient by BeDatse.</strong>

**Comment by jrrcdev** [comment]
Comentario novo

<strong>Posted with GitClient by BeDatse.</strong>

**Comment by jrrcdev** [comment]
Tewst

**Comment by gusttavosouza** [comment]
gyjugyjg

**Comment by testeAccount** [comment]
Que coisa
